resource_group_name      = "UC1-PricingService"
resource_pricing_service = "rg-pricingservice-dev-001"
cluster_name             = "qarpsclstr2"
mssql_name               = "mssqlpricingqa"
mssql_full_name          = "mssqlpricingqa.privatelink.database.windows.net"
key_vault_name           = "akv-pricingservice-dev"