name: Build Application

on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - 'feature/**'
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Github Object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
          
      - name: Validate Dependabot
        if: ${{ env.ARM_CLIENT_ID != '' }} && ${{ github.actor != "lcorrea21" }}
        run: echo "El actor ${{ github.actor }} no es un Dependabot"

      - name: Get branch name (merge)
        if: |
          github.event_name != 'pull_request' &&
          (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release')
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr [:upper:] [:lower:] | tr /_ - | cut -d "-" -f 2-3)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: |
          github.event_name == 'pull_request' &&
          github.ref != 'refs/heads/master'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr [:upper:] [:lower:])" >> $GITHUB_ENV
        
      - name: Debug
        id: debug
        run: echo  "BRANCH_RPS_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT

      - name: Test
        id: test
        run: echo  "TF_VAR_http=https://${{ env.BRANCH_NAME }}-qa.rps.revalizesoftware.com/graphql"
