name: Terraform Deployment

on:
  workflow_run:
    workflows: [ Build Application ]
    types: [ completed ]
    branches:
      - master
      - release
      - 'feature/**'
  workflow_dispatch: #this attribute will enable the manual run to the pipeline

jobs:
  reusable_workflow:
    uses: ./.github/workflows/main.yml
    
  load_variables:
    runs-on: ubuntu-latest
    needs: reusable_workflow
    env:
      BRANCH_NAME2: ${{needs.reusable_workflow.outputs.branch_rps_name}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Github Object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
    
      - name: Get branch name (main)
        if: |
          (github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'push' || github.event_name == 'workflow_dispatch')  &&
          github.event.workflow_run.head_branch == 'master'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr [:upper:] [:lower:] | tr /_ - | cut -d "-" -f 2-3)" >> $GITHUB_ENV

      - name: Get branch name other branch
        if: |
          (github.event.workflow_run.event == 'pull_request' || github.event_name == 'workflow_dispatch') && env.BRANCH_NAME2 != 'master' && env.BRANCH_NAME2 != 'release'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${{ env.BRANCH_NAME2 }} | tr [:upper:] [:lower:] | tr /_ - | cut -d "-" -f 2-3)" >> $GITHUB_ENV

      - name: Debug
        id: debug
        run: echo  "BRANCH_RPS_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT
