name: Terraform Deployment

on:
  workflow_run:
    workflows: [ Build Application ]
    types: [ completed ]
    branches:
      - master
      - release
      - 'feature/**'
  workflow_dispatch: #this attribute will enable the manual run to the pipeline

env:
  MASTER_HEAD_BRANCH: ${{ contains(github.event.workflow_run.pull_requests[0].head.ref, 'master') && true || false }}

jobs:   
  load_variables:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && (contains(github.event.workflow_run.pull_requests[0].head.ref, 'master') && true || false) == false }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Github Object
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
    
      - name: Get branch name (main)
        if: |
          (github.event.workflow_run.event == 'push' || github.event_name == 'workflow_dispatch') && github.event.workflow_run.head_branch == 'master'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr [:upper:] [:lower:] | tr /_ - | cut -d "-" -f 2-3)" >> $GITHUB_ENV

      - name: Get branch name other branch
        if: |
          (github.event.workflow_run.event == 'pull_request' || github.event_name == 'workflow_dispatch') &&
          github.event.workflow_run.head_branch != 'master'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${{ github.event.workflow_run.head_branch }} | tr [:upper:] [:lower:] | tr /_ - | cut -d "-" -f 2-3)" >> $GITHUB_ENV

      - name: Debug
        id: debug
        run: echo  "BRANCH_RPS_NAME=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT
